# Generated by Django 4.1.2 on 2022-11-16 18:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('trailsapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='menu',
            table='new_menu',
        ),
    ]
