# Generated by Django 4.1.2 on 2022-12-12 05:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trailsapp', '0003_trails_delete_item_delete_menu'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='trails',
            name='id',
        ),
        migrations.AlterField(
            model_name='trails',
            name='trail_id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
