# Generated by Django 4.1.2 on 2022-12-12 15:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('trailsapp', '0004_remove_trails_id_alter_trails_trail_id'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='trails',
            table='trails',
        ),
    ]
