# Generated by Django 4.1.2 on 2022-12-12 18:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trailsapp', '0005_alter_trails_table'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trails',
            name='img_url',
            field=models.CharField(max_length=500),
        ),
    ]
