# Generated by Django 4.1.2 on 2022-12-12 18:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('trailsapp', '0006_alter_trails_img_url'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='trails',
            name='img_url',
        ),
    ]
